# Generated by Django 5.2.7 on 2025-11-03 20:37

import apps.courses.fields.order_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_file_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='image',
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=apps.courses.fields.order_field.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=apps.courses.fields.order_field.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
