# Generated by Django 5.2.7 on 2025-11-03 21:45

import apps.courses.fields.automatic_slug
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_file_image_image_content_order_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=apps.courses.fields.automatic_slug.AutomaticSlugField(unique=True),
        ),
    ]
