# Generated by Django 5.2.7 on 2025-11-03 22:06

import apps.courses.fields.automatic_slug
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=apps.courses.fields.automatic_slug.AutomaticSlugField(),
        ),
    ]
